services:
  db:
    image: postgres
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: exampledb
      POSTGRES_USER: example
      POSTGRES_PASSWORD: secret
    volumes:
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d:ro
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: {}

